version: 0.2

phases:
  install:
    runtime-versions:
     python: 3.7

  build:
    commands:
      - pip install --upgrade pip
      - pip install --upgrade awscli
      - pip install --upgrade aws-sam-cli
      - sam build -b .aws-sam/build
      - sam package --s3-bucket $S3_BUCKET --template-file .aws-sam/build/template.yaml --output-template-file template-export.yml

artifacts:
  type: zip
  files:
    - template-export.yml
    - template-configuration.json